import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Radiant Glow Serum',
    description: 'A powerful serum to boost your skin\'s natural radiance.',
    longDescription: 'Our Radiant Glow Serum is packed with Vitamin C and Hyaluronic Acid to brighten, hydrate, and rejuvenate your skin. Lightweight and fast-absorbing, it targets dark spots and dullness for a visibly brighter complexion.',
    price: 45.00,
    salePrice: 38.00,
    rating: 4.8,
    reviewCount: 152,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['vegan', 'hydrating', 'brightening'],
    quantity: 50,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    name: 'Velvet Matte Lipstick',
    description: 'A long-lasting, highly pigmented matte lipstick.',
    longDescription: 'Experience bold, beautiful color with our Velvet Matte Lipstick. The creamy, non-drying formula glides on smoothly and sets to a comfortable, long-wearing matte finish. Available in 12 stunning shades.',
    price: 22.00,
    salePrice: null,
    rating: 4.5,
    reviewCount: 230,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['long-lasting', 'matte', 'cruelty-free'],
    quantity: 100,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    name: 'Hydrating Hair Mask',
    description: 'An intensive treatment to nourish and repair dry, damaged hair.',
    longDescription: 'Restore your hair\'s health and shine with our Hydrating Hair Mask. Enriched with argan oil and shea butter, this deep conditioning treatment detangles, softens, and revitalizes stressed hair.',
    price: 32.00,
    salePrice: null,
    rating: 4.9,
    reviewCount: 98,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['repairing', 'hydrating', 'sulfate-free'],
    quantity: 30,
    deliveryTime: '3-5 business days',
    brand: 'LuxeLocks',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    name: 'Midnight Bloom Eau de Parfum',
    description: 'A captivating and mysterious floral fragrance.',
    longDescription: 'Unveil your mysterious side with Midnight Bloom. This enchanting Eau de Parfum features notes of black currant, night-blooming jasmine, and vanilla for a scent that is both alluring and unforgettable.',
    price: 85.00,
    salePrice: 75.00,
    rating: 4.7,
    reviewCount: 188,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['floral', 'luxury', 'long-lasting'],
    quantity: 25,
    deliveryTime: '2-3 business days',
    brand: 'AuraScents',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
    {
    id: 'prod_5',
    name: 'Purifying Clay Cleanser',
    description: 'A gentle yet effective clay cleanser for all skin types.',
    longDescription: 'Detoxify your skin without stripping its natural moisture. Our Purifying Clay Cleanser uses kaolin clay to draw out impurities, while aloe vera and green tea soothe and protect the skin.',
    price: 28.00,
    salePrice: null,
    rating: 4.6,
    reviewCount: 112,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['purifying', 'gentle', 'all-skin-types'],
    quantity: 75,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    name: 'Luminous Liquid Foundation',
    description: 'A buildable, medium-coverage foundation with a natural, dewy finish.',
    longDescription: 'Achieve a flawless, radiant complexion with our Luminous Liquid Foundation. The lightweight formula blends seamlessly, evening out skin tone and providing a healthy, dewy glow that lasts all day.',
    price: 38.00,
    salePrice: null,
    rating: 4.4,
    reviewCount: 195,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['dewy-finish', 'medium-coverage', 'hydrating'],
    quantity: 60,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_7',
    name: 'Volumizing Dry Shampoo',
    description: 'Instantly refreshes hair and adds volume between washes.',
    longDescription: 'Extend the life of your blowout with our Volumizing Dry Shampoo. This weightless spray absorbs oil, eliminates odor, and adds instant texture and lift for hair that looks and feels clean.',
    price: 18.00,
    salePrice: 15.00,
    rating: 4.3,
    reviewCount: 310,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['volume', 'refreshing', 'vegan'],
    quantity: 80,
    deliveryTime: '3-5 business days',
    brand: 'LuxeLocks',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_8',
    name: 'Sun-kissed Citrus Body Mist',
    description: 'A light and refreshing body mist with a zesty citrus scent.',
    longDescription: 'Energize your senses with our Sun-kissed Citrus Body Mist. A spritz of this invigorating mist leaves you feeling refreshed and lightly scented with notes of mandarin, grapefruit, and bergamot.',
    price: 25.00,
    salePrice: null,
    rating: 4.5,
    reviewCount: 75,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['citrus', 'refreshing', 'light-fragrance'],
    quantity: 120,
    deliveryTime: '2-3 business days',
    brand: 'AuraScents',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const orders: Order[] = [];
