import type { Product, Order } from './types';

export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Radiant Glow Serum',
    description: 'A powerful serum to boost your skin\'s natural radiance.',
    longDescription: 'Our Radiant Glow Serum is packed with Vitamin C and Hyaluronic Acid to brighten and hydrate your skin. It fights dullness, evens out skin tone, and leaves you with a luminous, healthy-looking complexion. Suitable for all skin types.',
    price: 45.00,
    salePrice: 39.99,
    rating: 4.8,
    reviewCount: 178,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['vegan', 'hydrating', 'brightening'],
    quantity: 50,
    deliveryTime: '2-3 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-26T10:00:00Z'),
    updatedAt: new Date('2023-10-26T10:00:00Z'),
  },
  {
    id: 'prod_2',
    name: 'Velvet Matte Lipstick',
    description: 'A long-lasting, comfortable matte lipstick in a universal nude.',
    longDescription: 'Experience the perfect pout with our Velvet Matte Lipstick. The creamy, non-drying formula glides on smoothly and sets to a beautiful matte finish that lasts for hours without feathering or fading. The shade "Timeless" is a universally flattering nude.',
    price: 24.00,
    salePrice: null,
    rating: 4.6,
    reviewCount: 254,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['matte', 'long-lasting', 'cruelty-free'],
    quantity: 100,
    deliveryTime: '2-3 business days',
    brand: 'EVQ Cosmetics',
    createdAt: new Date('2023-10-25T11:30:00Z'),
    updatedAt: new Date('2023-10-25T11:30:00Z'),
  },
   {
    id: 'prod_3',
    name: 'Hydra-Silk Hair Mask',
    description: 'An intensive treatment to restore moisture and shine to dry, damaged hair.',
    longDescription: 'Revive your locks with the Hydra-Silk Hair Mask. Enriched with argan oil and keratin proteins, this luxurious treatment deeply conditions, detangles, and repairs damaged hair, leaving it silky smooth, manageable, and full of life.',
    price: 32.00,
    salePrice: null,
    rating: 4.9,
    reviewCount: 98,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['repairing', 'hydrating', 'sulfate-free'],
    quantity: 30,
    deliveryTime: '3-5 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-24T09:00:00Z'),
    updatedAt: new Date('2023-10-24T09:00:00Z'),
  },
  {
    id: 'prod_4',
    name: 'Ocean Breeze Eau de Parfum',
    description: 'A fresh and invigorating fragrance inspired by the sea.',
    longDescription: 'Capture the essence of a coastal getaway with Ocean Breeze. This captivating Eau de Parfum features notes of sea salt, jasmine, and driftwood, creating a scent that is both uplifting and sophisticated. Perfect for everyday wear.',
    price: 75.00,
    salePrice: 65.00,
    rating: 4.7,
    reviewCount: 120,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['fresh', 'citrus', 'unisex'],
    quantity: 60,
    deliveryTime: '2-3 business days',
    brand: 'Aura Scents',
    createdAt: new Date('2023-10-22T14:00:00Z'),
    updatedAt: new Date('2023-10-22T14:00:00Z'),
  },
  // Add 8 more mock products
  {
    id: 'prod_5',
    name: 'Purifying Clay Cleanser',
    description: 'A gentle yet effective cleanser to detoxify pores.',
    longDescription: 'Our Purifying Clay Cleanser uses kaolin clay to draw out impurities without stripping the skin. Infused with calming chamomile and tea tree oil, it leaves your skin feeling clean, balanced, and refreshed. Ideal for normal to oily skin types.',
    price: 28.00,
    salePrice: null,
    rating: 4.5,
    reviewCount: 210,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['detox', 'balancing', 'clay'],
    quantity: 75,
    deliveryTime: '2-3 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-20T10:00:00Z'),
    updatedAt: new Date('2023-10-20T10:00:00Z'),
  },
  {
    id: 'prod_6',
    name: 'Lash Volumizing Mascara',
    description: 'For bold, dramatic lashes with a single swipe.',
    longDescription: 'Achieve ultimate volume and length with this jet-black mascara. The specially designed brush coats every lash from root to tip, creating a full, fan-like effect without clumping or smudging. Water-resistant and buildable formula.',
    price: 22.00,
    salePrice: null,
    rating: 4.7,
    reviewCount: 312,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['volume', 'lengthening', 'water-resistant'],
    quantity: 150,
    deliveryTime: '1-2 business days',
    brand: 'EVQ Cosmetics',
    createdAt: new Date('2023-10-18T12:00:00Z'),
    updatedAt: new Date('2023-10-18T12:00:00Z'),
  },
  {
    id: 'prod_7',
    name: 'Growth & Strength Hair Oil',
    description: 'A nourishing blend of oils to promote healthy hair growth.',
    longDescription: 'This lightweight hair oil is a potent blend of castor, rosemary, and peppermint oils known to stimulate the scalp and strengthen hair follicles. Use it as a pre-shampoo treatment or a leave-in conditioner for stronger, healthier hair.',
    price: 25.00,
    salePrice: 22.50,
    rating: 4.8,
    reviewCount: 85,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['strengthening', 'growth', 'natural'],
    quantity: 40,
    deliveryTime: '3-5 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-15T09:30:00Z'),
    updatedAt: new Date('2023-10-15T09:30:00Z'),
  },
  {
    id: 'prod_8',
    name: 'Sunset Fleur Perfume Oil',
    description: 'A warm, floral roll-on perfume for on-the-go.',
    longDescription: 'A concentrated perfume oil with notes of gardenia, amber, and vanilla. Its compact, roll-on design makes it perfect for travel or touch-ups throughout the day, leaving a warm and intoxicating scent on the skin.',
    price: 30.00,
    salePrice: null,
    rating: 4.6,
    reviewCount: 77,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['floral', 'warm', 'travel-size'],
    quantity: 90,
    deliveryTime: '2-3 business days',
    brand: 'Aura Scents',
    createdAt: new Date('2023-10-12T16:00:00Z'),
    updatedAt: new Date('2023-10-12T16:00:00Z'),
  },
    {
    id: 'prod_9',
    name: 'Overnight Recovery Cream',
    description: 'A rich night cream that repairs and regenerates skin while you sleep.',
    longDescription: 'Wake up to revitalized skin with our Overnight Recovery Cream. Formulated with peptides and ceramides, it works to repair the skin\'s moisture barrier, reduce the appearance of fine lines, and restore firmness overnight. Perfect for mature or dry skin.',
    price: 55.00,
    salePrice: 48.00,
    rating: 4.9,
    reviewCount: 150,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['anti-aging', 'repairing', 'night-cream'],
    quantity: 45,
    deliveryTime: '2-3 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-10T20:00:00Z'),
    updatedAt: new Date('2023-10-10T20:00:00Z'),
  },
  {
    id: 'prod_10',
    name: 'HD Finish Setting Powder',
    description: 'A translucent powder that sets makeup for a flawless, airbrushed finish.',
    longDescription: 'This finely-milled, translucent setting powder blurs imperfections and sets your makeup for all-day wear. It controls shine without adding weight or texture, giving you a photo-ready, high-definition finish. Comes with a powder puff for easy application.',
    price: 30.00,
    salePrice: null,
    rating: 4.7,
    reviewCount: 401,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['translucent', 'setting', 'oil-control'],
    quantity: 80,
    deliveryTime: '1-2 business days',
    brand: 'EVQ Cosmetics',
    createdAt: new Date('2023-10-08T11:00:00Z'),
    updatedAt: new Date('2023-10-08T11:00:00Z'),
  },
  {
    id: 'prod_11',
    name: 'Color-Protect Shampoo',
    description: 'A gentle shampoo to protect color-treated hair from fading.',
    longDescription: 'Keep your hair color vibrant with our Color-Protect Shampoo. This sulfate-free formula gently cleanses without stripping color, while UV filters and antioxidants protect against environmental damage and fading. Leaves hair soft, shiny, and vibrant.',
    price: 26.00,
    salePrice: null,
    rating: 4.5,
    reviewCount: 130,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['color-safe', 'uv-protect', 'sulfate-free'],
    quantity: 65,
    deliveryTime: '3-5 business days',
    brand: 'EVANIEGLOW',
    createdAt: new Date('2023-10-05T10:00:00Z'),
    updatedAt: new Date('2023-10-05T10:00:00Z'),
  },
  {
    id: 'prod_12',
    name: 'Midnight Oud Cologne',
    description: 'A mysterious and spicy fragrance for the modern man.',
    longDescription: 'An intense and alluring cologne with notes of oud, black pepper, and leather. Midnight Oud is a bold statement fragrance that is perfect for evening wear and special occasions, leaving a lasting impression.',
    price: 85.00,
    salePrice: null,
    rating: 4.8,
    reviewCount: 95,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['spicy', 'woody', 'masculine'],
    quantity: 55,
    deliveryTime: '2-3 business days',
    brand: 'Aura Scents',
    createdAt: new Date('2023-10-01T18:00:00Z'),
    updatedAt: new Date('2023-10-01T18:00:00Z'),
  },
];


export const mockOrders: Order[] = [
    {
        id: 'order_1',
        userId: 'user_1',
        createdAt: new Date('2023-10-28T14:30:00Z'),
        updatedAt: new Date('2023-10-28T14:30:00Z'),
        total: 63.99,
        status: 'Delivered',
        transactionId: 'txn_12345',
        shippingAddress: {
            name: 'Jane Doe',
            address: '123 Glow St',
            city: 'Beautyville',
            state: 'CA',
            zip: '90210',
            country: 'USA'
        },
        items: [
            { id: 'item_1', orderId: 'order_1', productId: 'prod_1', quantity: 1, price: 39.99 },
            { id: 'item_2', orderId: 'order_1', productId: 'prod_2', quantity: 1, price: 24.00 },
        ]
    },
    {
        id: 'order_2',
        userId: 'user_1',
        createdAt: new Date('2023-09-15T10:00:00Z'),
        updatedAt: new Date('2023-09-15T10:00:00Z'),
        total: 32.00,
        status: 'Paid',
        transactionId: 'txn_67890',
        shippingAddress: {
            name: 'Jane Doe',
            address: '123 Glow St',
            city: 'Beautyville',
            state: 'CA',
            zip: '90210',
            country: 'USA'
        },
        items: [
            { id: 'item_3', orderId: 'order_2', productId: 'prod_3', quantity: 1, price: 32.00 },
        ]
    }
];
