
import type { Product, Order, User } from './types';

export const mockUsers: User[] = [
    { id: 'mock-user-1', email: 'customer@example.com', name: 'John Doe', role: 'CUSTOMER' },
    { id: 'mock-admin-uid', email: 'admin@example.com', name: 'Admin User', role: 'ADMIN' },
]

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Radiant Glow Serum',
    description: 'A powerful serum for a youthful glow.',
    longDescription: 'Our Radiant Glow Serum is packed with vitamin C and antioxidants to brighten your skin, reduce fine lines, and give you a healthy, youthful glow. Suitable for all skin types.',
    price: 45.00,
    salePrice: 39.99,
    rating: 4.8,
    reviewCount: 150,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['vegan', 'hydrating', 'serum'],
    quantity: 100,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    name: 'Velvet Matte Lipstick',
    description: 'A long-lasting, smudge-proof lipstick.',
    longDescription: 'Experience the luxury of our Velvet Matte Lipstick. This highly pigmented formula glides on smoothly and delivers a beautiful matte finish that lasts all day without drying out your lips.',
    price: 22.50,
    salePrice: null,
    rating: 4.5,
    reviewCount: 210,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['matte', 'long-lasting', 'lipstick'],
    quantity: 250,
    deliveryTime: '2-3 business days',
    brand: 'Belleza',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'prod_3',
    name: 'Hydrating Hair Mask',
    description: 'Deeply conditions and revitalizes hair.',
    longDescription: 'Treat your hair to our Hydrating Hair Mask. Enriched with argan oil and shea butter, it deeply nourishes, repairs damage, and leaves your hair feeling soft, shiny, and manageable.',
    price: 35.00,
    salePrice: null,
    rating: 4.7,
    reviewCount: 85,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['hydrating', 'repair', 'hair mask'],
    quantity: 80,
    deliveryTime: '3-5 business days',
    brand: 'Alegreya',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'prod_4',
    name: 'Enchanting Bloom Perfume',
    description: 'A captivating floral fragrance.',
    longDescription: 'Discover Enchanting Bloom, a sophisticated fragrance with notes of jasmine, rose, and sandalwood. This elegant scent is perfect for any occasion and leaves a lasting impression.',
    price: 75.00,
    salePrice: 65.00,
    rating: 4.9,
    reviewCount: 120,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['floral', 'luxury', 'perfume'],
    quantity: 50,
    deliveryTime: '2-3 business days',
    brand: 'GlowUp',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'prod_5',
    name: 'Clarifying Clay Cleanser',
    description: 'Purifies pores and controls excess oil.',
    longDescription: 'Our Clarifying Clay Cleanser, formulated with kaolin clay and tea tree oil, draws out impurities, reduces shine, and helps prevent breakouts for a clearer, balanced complexion.',
    price: 28.00,
    salePrice: null,
    rating: 4.6,
    reviewCount: 95,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['oily skin', 'cleanser', 'purifying'],
    quantity: 120,
    deliveryTime: '2-3 business days',
    brand: 'Alegreya',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: 'prod_6',
    name: 'Luminous Foundation',
    description: 'A lightweight foundation for a natural finish.',
    longDescription: 'Achieve a flawless, radiant complexion with our Luminous Foundation. This buildable, lightweight formula provides medium coverage and a natural, dewy finish that looks and feels like second skin.',
    price: 40.00,
    salePrice: null,
    rating: 4.7,
    reviewCount: 180,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['foundation', 'radiant', 'lightweight'],
    quantity: 200,
    deliveryTime: '2-3 business days',
    brand: 'Belleza',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  }
];

export const orders: Order[] = [
    {
        id: 'ord_1',
        userId: 'mock-user-1',
        items: [
            { id: 'item_1', orderId: 'ord_1', productId: 'prod_1', quantity: 1, price: 39.99, product: products[0] },
            { id: 'item_2', orderId: 'ord_1', productId: 'prod_2', quantity: 2, price: 22.50, product: products[1] },
        ],
        total: 84.99,
        status: 'Paid',
        shippingAddress: JSON.stringify({ name: 'John Doe', address: '123 Main St', city: 'Anytown', state: 'CA', zip: '12345', country: 'USA' }),
        transactionId: 'txn_12345',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
        user: mockUsers[0],
    },
    {
        id: 'ord_2',
        userId: 'mock-admin-uid',
        items: [
            { id: 'item_3', orderId: 'ord_2', productId: 'prod_4', quantity: 1, price: 65.00, product: products[3] },
        ],
        total: 65.00,
        status: 'Processing',
        shippingAddress: JSON.stringify({ name: 'Admin User', address: '456 Admin Ave', city: 'Control Panel', state: 'NY', zip: '54321', country: 'USA' }),
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
        updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
        user: mockUsers[1],
    }
];
