import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Hydrating Rosewater Mist',
    brand: 'Petal Fresh',
    description: 'A refreshing facial mist for a dewy glow.',
    longDescription: 'Revitalize your skin with our Hydrating Rosewater Mist. Made with pure rosewater, this mist tones, hydrates, and refreshes the skin, leaving it with a dewy, luminous finish. Perfect for setting makeup or as a mid-day pick-me-up.',
    price: 24.99,
    rating: 4.8,
    reviewCount: 215,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['hydrating', 'vegan', 'toner'],
  },
  {
    id: '2',
    name: 'Velvet Matte Lipstick',
    brand: 'Luxe Lips',
    description: 'A long-lasting, highly pigmented matte lipstick.',
    longDescription: 'Experience bold, beautiful color with our Velvet Matte Lipstick. The creamy, non-drying formula glides on smoothly and sets to a stunning matte finish that lasts all day. Available in 12 vibrant shades.',
    price: 18.0,
    rating: 4.5,
    reviewCount: 302,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['matte', 'long-lasting', 'lips'],
  },
  {
    id: '3',
    name: 'Argan Oil Hair Serum',
    brand: 'Silken Strands',
    description: 'Nourishes and tames frizzy, dry hair.',
    longDescription: 'Transform your hair with our Argan Oil Hair Serum. This lightweight, non-greasy formula is infused with antioxidant-rich argan oil to smooth frizz, add shine, and protect against heat damage. Your hair will feel soft, silky, and manageable.',
    price: 32.5,
    rating: 4.9,
    reviewCount: 188,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['anti-frizz', 'shine', 'serum'],
  },
  {
    id: '4',
    name: 'Eau de Parfum - Fleur',
    brand: 'Maison de Senteur',
    description: 'A delicate and romantic floral fragrance.',
    longDescription: 'Fall in love with Fleur, our signature Eau de Parfum. This enchanting fragrance features notes of jasmine, peony, and white musk, creating a scent that is both timeless and modern. Perfect for any occasion.',
    price: 85.0,
    rating: 4.7,
    reviewCount: 95,
    category: 'Fragrance',
    images: ['https://placehold.co/600x600.png'],
    tags: ['floral', 'luxury', 'perfume'],
  },
  {
    id: '5',
    name: 'Vitamin C Brightening Serum',
    brand: 'GlowUp Essentials',
    description: 'Fades dark spots and boosts radiance.',
    longDescription: 'Achieve a brighter, more even-toned complexion with our Vitamin C Brightening Serum. Formulated with a stable form of Vitamin C and hyaluronic acid, this serum targets dullness and discoloration while providing intense hydration.',
    price: 45.0,
    rating: 4.6,
    reviewCount: 412,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['brightening', 'vitamin-c', 'serum'],
  },
  {
    id: '6',
    name: 'Luminous Glow Foundation',
    brand: 'Aura Beauty',
    description: 'A medium-coverage foundation with a radiant finish.',
    longDescription: 'Get a flawless, lit-from-within glow with our Luminous Glow Foundation. This buildable, medium-coverage formula evens out skin tone and blurs imperfections, leaving your skin looking naturally radiant and healthy.',
    price: 38.0,
    rating: 4.4,
    reviewCount: 520,
    category: 'Makeup',
    images: ['https://placehold.co/600x600.png'],
    tags: ['foundation', 'radiant', 'medium-coverage'],
  },
  {
    id: '7',
    name: 'Keratin Repair Hair Mask',
    brand: 'Silken Strands',
    description: 'Deeply conditions and strengthens damaged hair.',
    longDescription: 'Restore your hair\'s health and vitality with our Keratin Repair Hair Mask. This intensive treatment is enriched with keratin and natural oils to repair damage, reduce breakage, and leave hair feeling soft, strong, and revitalized.',
    price: 28.0,
    rating: 4.8,
    reviewCount: 154,
    category: 'Haircare',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    tags: ['repair', 'deep-conditioning', 'mask'],
  },
  {
    id: '8',
    name: 'Cleansing Balm',
    brand: 'Petal Fresh',
    description: 'Melts away makeup and impurities.',
    longDescription: 'Effortlessly dissolve makeup, sunscreen, and impurities with our gentle Cleansing Balm. This sorbet-like balm transforms into a silky oil upon application, cleansing the skin without stripping its natural moisture. Leaves skin feeling clean, soft, and hydrated.',
    price: 29.99,
    rating: 4.9,
    reviewCount: 350,
    category: 'Skincare',
    images: ['https://placehold.co/600x600.png'],
    tags: ['cleanser', 'makeup-remover', 'hydrating'],
  },
];
