
import { generateBlogPost } from '@/ai/flows/generate-blog-post';
import { Card, CardContent } from '@/components/ui/card';
import { Calendar, BrainCircuit, Search } from 'lucide-react';
import { notFound } from 'next/navigation';

// Sample topics to match the blog index page
const blogTopics = [
  { topic: 'The Ultimate Guide to a Flawless Foundation Routine', slug: 'ultimate-guide-flawless-foundation' },
  { topic: '5 Must-Have Skincare Ingredients for Radiant Skin', slug: '5-must-have-skincare-ingredients' },
  { topic: 'Decoding Makeup Brushes: A Beginner\'s Guide', slug: 'decoding-makeup-brushes' },
  { topic: 'Top 7 Summer Hair Care Tips to Beat the Heat', slug: 'summer-hair-care-tips' },
  { topic: 'The Rise of Sustainable Beauty: What You Need to Know', slug: 'sustainable-beauty-rise' },
  { topic: 'How to Find the Perfect Nude Lipstick for Your Skin Tone', slug: 'perfect-nude-lipstick' },
];

export default async function BlogPostPage({ params }: { params: { slug: string } }) {
  const postInfo = blogTopics.find((p) => p.slug === params.slug);

  if (!postInfo) {
    notFound();
  }

  const post = await generateBlogPost(postInfo.topic);

  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 max-w-4xl">
      <article>
        <header className="mb-8">
          <h1 className="font-headline text-4xl md:text-5xl font-bold mb-4 leading-tight">{post.title}</h1>
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
             <div className="flex items-center gap-2">
                <BrainCircuit className="h-4 w-4 text-primary" />
                <span>Generated by Evanie Glow AI</span>
             </div>
             <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-primary" />
                <time dateTime={new Date().toISOString()}>
                    {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                </time>
             </div>
          </div>
        </header>

         <Card className="bg-card/50 backdrop-blur-sm border-border/20">
            <CardContent>
                 <div 
                    className="prose dark:prose-invert max-w-none text-muted-foreground py-6"
                    dangerouslySetInnerHTML={{ __html: post.content }}
                />
            </CardContent>
        </Card>
        
        <div className="mt-8 border-t border-border/20 pt-4">
            <h3 className="text-lg font-semibold flex items-center gap-2">
                <Search className="h-5 w-5 text-primary" />
                AI Search Sources
            </h3>
            <p className="text-sm text-muted-foreground mt-2 mb-4">
                This article was generated by AI using the following top search results as sources.
            </p>
            <ul className="space-y-2 text-sm">
                {post.sources.map((source, index) => (
                    <li key={index} className="flex items-start gap-2">
                        <span className="text-primary pt-1">●</span>
                        <a href={source} target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors truncate">
                            {source}
                        </a>
                    </li>
                ))}
            </ul>
        </div>
      </article>
    </div>
  );
}
